name: mitiq-mybinder-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - qiskit-terra~=0.18.1
    - qiskit-aer~=0.8.2
    - qiskit-ibmq-provider~=0.16.0
    - pyquil~=2.28.0
    - amazon-braket-sdk~=1.8.0
    - pytest-xdist[psutil]~=2.3.0
    - pytest-cov~=2.12.1
    - flake8~=3.9.2
    - black~=19.10b0
    - mypy~=0.910
    - sphinxcontrib-bibtex~=2.3.0
    - sphinx-copybutton~=0.3.0
    - sphinx-autodoc-typehints~=1.12.0
    - myst-nb~=0.12.3
    - pydata-sphinx-theme~=0.6.3
    - jupytext
